FROM kineticsquid/aws-lambda-automation-base:latest

ARG FUNCTION_DIR="/function"

COPY automation-aws.py ${FUNCTION_DIR}

WORKDIR ${FUNCTION_DIR}
RUN date > ${FUNCTION_DIR}/build.txt

ENTRYPOINT [ "/entry_script.sh" ]

CMD [ "automation-aws.handler" ]
